### ISSUE TITLE
Unable to find http://rgerganov.github.io/noVNC/6

### ISSUE THREAD

**Issue by rushikeshjadhav** [rgerganov/mks#2]
@rgerganov 

While trying to get mks.py work, it seems to be asking to open http://rgerganov.github.io/noVNC/6/ or http://rgerganov.github.io/noVNC/5/ however both links are 404 at this moment.

Where can I explore them ?

**Comment by rgerganov** [comment]
The files are there, you are getting 404 because there is no index.html.  Try:
http://rgerganov.github.io/noVNC/6/vnc_auto.html

You can explore all files at: https://github.com/rgerganov/noVNC/tree/gh-pages
