### ISSUE TITLE
Not able to establish mks connection by hosting noVNC on local system

### ISSUE THREAD

**Issue by satwikk** [rgerganov/mks#3]
How can I setup mks connection by hosting noVNC on my local machine? I am not able to establish ws connection with esxi host when I use "localhost/noVNC" instead of "https://rgerganov.github.io/noVNC/6/". When I use your github noVNC link, I am able to establish a mks connection with ESXi 6 host (for which there is no need to run websockify proxy), but not able to do the same with "localhost/noVNC". Where I get this error "Server disconnected (code: 1006)"

Following is the Firebug screenshot after a failed connection.

![image](https://cloud.githubusercontent.com/assets/11518589/18168271/807e2e1c-7072-11e6-9f13-2878c9a4e86d.png)

Note: On my local system I have downloaded noVNC from this "https://github.com/rgerganov/noVNC/tree/gh-pages/"
I have one ESXi 6.0 host in my private environment.

**Comment by rgerganov** [comment]
Can you try serving noVNC from HTTPS (instead of HTTP) and see if it works?

**Comment by satwikk** [comment]
@rgerganov Yes, that was it! ESXi was not accepting traffic over http/ws, But everything works fine on HTTPS. Thanks for your assistance, Cheers buddy!
